
function setup_wind_blown_particles(sprite, effect_layer_name){
	var _fx_wind_blown_particles = fx_create("_effect_windblown_particles");
	fx_set_parameter(_fx_wind_blown_particles, "param_sprite", sprite);
	layer_set_fx(effect_layer_name, _fx_wind_blown_particles);
	/*
	----- PARAMETER LIST -------------
	param_sprite (Sprite)
	param_num_particles (Real)
	param_particle_spawn_time (Real)
	param_particle_spawn_all_at_start (Bool)
	param_warmup_frames (Real)
	param_particle_mass_min (Real)
	param_particle_mass_max (Real)
	param_particle_start_sprite_scale (Real)
	param_particle_end_sprite_scale (Real)
	param_particle_col_1 (Array)
	param_particle_col_alt_1 (Array)
	param_particle_col_2 (Array)
	param_particle_col_alt_2 (Array)
	param_particle_col_2_pos (Real)
	param_particle_col_enabled_2 (Bool)
	param_particle_col_3 (Array)
	param_particle_col_alt_3 (Array)
	param_particle_col_3_pos (Real)
	param_particle_col_enabled_3 (Bool)
	param_particle_col_4 (Array)
	param_particle_col_alt_4 (Array)
	param_particle_initial_velocity_range_x_min (Real)
	param_particle_initial_velocity_range_x_max (Real)
	param_particle_initial_velocity_range_y_min (Real)
	param_particle_initial_velocity_range_y_max (Real)
	param_particle_initial_rotation_min (Real)
	param_particle_initial_rotation_max (Real)
	param_particle_rot_speed_min (Real)
	param_particle_rot_speed_max (Real)
	param_particle_align_vel (Real)
	param_particle_lifetime_min (Real)
	param_particle_lifetime_max (Real)
	param_particle_update_skip (Real)
	param_particle_spawn_border_prop (Real)
	param_particle_src_blend (Blend Mode Factor Constant)
	param_particle_dest_blend (Blend Mode Factor Constant)
	param_trails_only (Bool)
	param_trail_chance (Real)
	param_trail_lifetime_min (Real)
	param_trail_lifetime_max (Real)
	param_trail_thickness_min (Real)
	param_trail_thickness_max (Real)
	param_trail_col_1 (Array)
	param_trail_col_alt_1 (Array)
	param_trail_col_2 (Array)
	param_trail_col_alt_2 (Array)
	param_trail_col_2_pos (Real)
	param_trail_col_enabled_2 (Bool)
	param_trail_col_3 (Array)
	param_trail_col_alt_3 (Array)
	param_trail_col_3_pos (Real)
	param_trail_col_enabled_3 (Bool)
	param_trail_col_4 (Array)
	param_trail_col_alt_4 (Array)
	param_trail_min_segment_length (Real)
	param_trail_src_blend (Blend Mode Factor Constant)
	param_trail_dest_blend (Blend Mode Factor Constant)
	param_num_blowers (Real)
	param_blower_size_min (Real)
	param_blower_size_max (Real)
	param_blower_speed_min (Real)
	param_blower_speed_max (Real)
	param_blower_rot_speed_min (Real)
	param_blower_rot_speed_max (Real)
	param_blower_force_min (Real)
	param_blower_force_max (Real)
	param_blower_camvec_scale (Real)
	param_force_grid_sizex (Real)
	param_force_grid_sizey (Real)
	param_wind_vector_x (Real)
	param_wind_vector_y (Real)
	param_dragcoeff (Real)
	param_grav_accel (Real)
	param_debug_grid (Bool)
	*/
}