function scr_fix_leg() {
	// This code is generated by KeeVee Games Fixture Editor.
	// Place this code in the Create event or similar.

	var fix, offsetx, offsety;

	offsetx = sprite_width/2-sprite_xoffset;
	offsety = sprite_height/2-sprite_yoffset;


	fix = physics_fixture_create();
	physics_fixture_set_box_shape(fix, parent.len_leg_w,parent.len_leg_h);

	  physics_fixture_set_density(fix, 0.50);
	  physics_fixture_set_friction(fix, 0.20);
	  physics_fixture_set_linear_damping(fix, 0.10);
	  physics_fixture_set_angular_damping(fix, 0.10);
	  physics_fixture_set_restitution(fix, 0.10);
	  physics_fixture_set_sensor(fix, 0);
	  physics_fixture_set_awake(fix, 1);
	  //physics_fixture_set_collision_group(fix,-1)
	  physics_fixture_bind_ext(fix, id, 0-offsetx, 0-offsety);
	  physics_fixture_delete(fix);



}
